name: 'Choreo Deployer'
description: 'Deploy newly built docker images to kubernetes through the Choreo API'
author: WSO2
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
inputs:
  domain:
    description: 'Choreo API Domain.'
    required: false
    default: ''
  org-id:
    description: 'Organization ID'
    required: true
    default: 0
  project-id:
    description: 'Project ID'
    required: true
    default: ''
  app-id:
    description: 'App ID'
    required: true
    default: ''
  env-id:
    description: 'Environment ID'
    required: true
    default: ''
  version:
    description: 'Version ID'
    required: true
    default: ''
  branch:
    description: 'Branch'
    required: false
    default: 'main'
  image-name: 
    description: 'Name of the image'
    required: true
    default: ''
  git-hash: 
    description: 'Name of the built tag'
    required: true
    default: 'latest'
  gitops-hash: 
    description: 'Name of the built tag of gitops repo'
    required: true
    default: 'latest'
  token: 
    description: 'Secret token for validation'
    required: true
    default: ''
  port-extract-file-path: 
    description: 'Deploymnet yaml file path to extract ports'
    required: true
    default: 'target/kubernetes/workspace/workspace.yaml'
  debug: 
    description: 'Enable request debug'
    required: false
    default: false
  is-http-based: 
    description: 'Status of the http based app'
    required: false
    default: false
outputs:
  choreo-status:
    description: 'Status of the Webhook Call to choreo'
runs:
  using: 'node16'
  main: 'index.js'
